In [32]:
result1 = []
for i in  range(10):
    result1.append(i)
result1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
result2 = [i for i in range(2,40,2)]
result2

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]

In [28]:
code = [(x,y)for x in range(3) for y in range(3)]
code

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

In [31]:
### 파일 입출력


In [17]:
import csv

In [21]:
import csv

with open('./부산시_해운대구_도서정보.csv', 'r', encoding='EUC-KR') as f:
    reader = csv.reader(f)

    for row in reader:
        print(row)

['번호', '서명', '저자', '발행자', '발행년', '청구기호', '자료실']
['1', '해럴드와 마법 크레용 [비디오녹화자료]', '카를로스 살다냐 감독', '소니 픽쳐스 홈엔터테인먼트 [공급]', '2025', 'DVD 688.2-2246', '[해운대인문학]디지털자료실']
['2', '나처럼 예쁜 여자 [비디오녹화자료]', '프랑수아 트뤼포 감독', 'Art Film [수입·제조]', '2024', 'DVD 688.2-2247', '[해운대인문학]디지털자료실']
['3', '조커 [비디오녹화자료] : 폴리 아 되', '토드 필립스 감독', '해리슨 앤 컴퍼니 [제조·판매]', '[2025]', 'DVD 688.2-2248', '[해운대인문학]디지털자료실']
['4', '신비아파트 고스트볼 ZERO [비디오녹화자료]. 2, 싹트는 울음소리, 뿌리 괴수의 진실', '박홍근 총감독', '뮤라인 [제작·판매]', '2025', 'DVD 688.6-1141-2', '[해운대인문학]디지털자료실']
['5', '마당을 나온 암탉 [비디오녹화자료]', '오성윤 감독', '미디어포유 [제작·판매]', '2025', 'DVD 688.6-335=2', '[해운대인문학]디지털자료실']
['6', '더 파일럿 [비디오녹화자료] : 드론 어택', '폴 듀세 감독', '미디어포유 [제작·판매]', '2025', 'DVD 688.2-2249', '[해운대인문학]디지털자료실']
['7', '새터데이 나이트 [비디오녹화자료]', '제이슨 라이트먼 감독', '소니 픽쳐스 홈엔터테인먼트 [공급]', '2025', 'DVD 688.2-2250', '[해운대인문학]디지털자료실']
['8', '구룡성채 [비디오녹화자료] : 무법지대', '정바오루이 감독', '플레인아카이브 [DVD 제작·판매]', '[2025]', 'DVD 688.2-2251', '[해운대인문학]디지털자료실']
['9', '신비아파트 고스트볼 ZERO [비디오녹화자료]. 3, 수상한 공사장의 비밀', '박홍근 총감독',

UnicodeDecodeError: 'euc_kr' codec can't decode byte 0x86 in position 324: illegal multibyte sequence

### Numpy
- 행렬이나 대규모 차원의 배열을 쉽게 처리하도록 지웒나느 파이썬 수치 라이브러리
- 수치 해석용 핵심 엔진 
- Scipy,SymPy관련 라이브러리
- Matplotlib 시각화 라이브러리
- Pandas 데이터 라이브러리

#### 설치
- 일반 콘솔 설치
````bash
pip install numpy
```


- 주피터 노트북 설치

```python
!pip install numpy
```

!pip install numpy

#### Python 기본 리스트와 Numpy 차이

a = [1,2,3]
b = [4,5,6]

res_list = [a[i] + b[i] for i in range(3)]
res_list

## Numpy 소스 코드에 포함 시킬때 보통 np라고 한다.
import numpy as np
na = np.array(a)
na

In [38]:
nb = np.array(b)
na + nb

array([5, 7, 9])

- numpy 배열은 배열로 형 변환 하면 + 연산으로 처리가 가능

In [ ]:
np.zeros(5) # 0인 5열 1차원 배열이 된다.

array([0., 0., 0., 0., 0.])

In [41]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
np.ones(4)

array([1., 1., 1., 1.])

In [43]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
[[0 for i in range(5)]for i in range(4)]

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [49]:
c = np.array([1,2,3,4,5])
c+10

array([11, 12, 13, 14, 15])

'충현이찡꼬'